version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    env_file:
      - .env  # Load .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"  
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - timescale_network
    restart: always

  bosch-sensor:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: bosch-sensor
    env_file:
      - .env  # Reference to the .env file
    depends_on:
      - timescaledb
    networks:
      - timescale_network
    volumes:
      - ./:/app
    working_dir: /app
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"  # Mount the host's /dev/ttyACM0 device into the container

  # Add Grafana service
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_bosch
    ports:
      - "3888:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DATA=/var/lib/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-datasources:/etc/grafana/provisioning/datasources
      - ./grafana/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - timescale_network
    depends_on:
      - timescaledb

networks:
  timescale_network:
    driver: bridge

volumes:
  timescale_data:
  grafana-storage:
  grafana-datasources:
